### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by alensiljak** [b-straub/DexieNET#1]
Hi!

Does anybody mind writing installation instructions that actually work? I'm not sure where the FriendsDB is expected to be found and how. Any hints on that part?
Thanks!

**Comment by b-straub** [comment]
I will create a sample app in the next days.

When you include the Nuget and create some code like

`
public partial record Friend
(
    [property: Index] string Name,
    [property: Index] int Age
) : IDBStore;
`

The source generator will generate a database stub named FriendsDB for you. The generated code can be found under "Dependencies/Analyzers/DexieNETTableGenerator/DNTGenerator.Generator" in VS.

**Comment by alensiljak** [comment]
Thank you! That was the missing piece. 
One should probably define the data access layer first, to have these generated, and then add them to Program.cs and the views.
