### ISSUE TITLE
bug: tsc : error TS18003: Build:No inputs were found in config file

### ISSUE THREAD

**Issue by abstract195** [b-straub/DexieNET#2]
after installing the nuget package the build fails with:

tsc : error TS18003: Build:No inputs were found in config file 'C:/Users/xxx/.nuget/packages/dexienet/1.0.0/contentFiles/any/net7.0/npm/tsconfig.json'. Specified 'include' paths were '["**/*.ts"]' and 'exclude' paths were '["node_modules"]'.

After creating an empty .ts file in the 'dexienet/1.0.0/contentFiles/any/net7.0/npm/src' it works.

**Comment by b-straub** [comment]
Thanks for the report. I can build fine and get only a warning but those files shouldn't be in the Nuget anyway. Will be solved along with .NET8.0 support in the near future.

**Comment by b-straub** [comment]
Fixed with latest release v1.0.1 through e56e30c
