### ISSUE TITLE
System.Text.Json 8.0.4 Vulnerability

### ISSUE THREAD

**Issue by mikehutter** [b-straub/DexieNET#4]
I'm probably missing something here, but I have a project that references System.Text.Json 8.0.5 because other packages require it because of the vulnerability in pretty much any version 8.0.4 and below. (see https://github.com/advisories/GHSA-8g4q-xg66-9fp4)

In the past with .NET/.NET Framework, just add the binding redirect and you're good. But from what I can discern, there really is no such way to manually add redirects in .NET Core. I thought .NET Core was supposed to do automatic binding redirects, but this doesn't appear to be happening and instead breaks the build.

WIndows 11
.NET 8.0.8
VS 2022 Enterprise

DNTGG000: Internal error 'Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

**Comment by b-straub** [comment]
I‘ll update the dependencies in the course of next week. Hope this will fix it.

**Comment by b-straub** [comment]
I did update all dependencies to latest stable versions for .NET 8.0, please recheck and close if working.

**Comment by b-straub** [comment]
Closing because no recent feedback, assume to be fixed by ba0462faaa7e205ac012a0cdf5e296d00a0c4bab
